Fixed #837 - Added margin in route_list_item.xml and stop_list_item.x…
OneBusAway/onebusaway-android pull request #1137
Opened 2024-03-03 19:41 UTC by GajananPalepwad

…ml to align with the header title

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

2024-03-03 19:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OneBusAway/onebusaway-android?pullRequest=1137) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OneBusAway/onebusaway-android?pullRequest=1137) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OneBusAway/onebusaway-android?pullRequest=1137) it.</sub>

2024-03-04 03:52 UTC, GajananPalepwad commented
I have signed the contribution license agreement but here not showing don't know why 
![Screenshot_2024-03-04-09-21-49-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/OneBusAway/onebusaway-android/assets/97339190/09f9899e-1c60-45bb-8923-1b51dfd73cb9)

2024-03-08 00:07 UTC, aaronbrethorst requested changes
Thank you for fixing this bug! Right now, it's hard for me to tell what is a code change and what's just reformatting. Can you redo this PR such that the only lines of XML that change are the ones where you are making the fix for #837?

2024-03-08 04:08 UTC, GajananPalepwad commented
Ok sir will fix it today only

2024-03-08 08:30 UTC, closed without merging