Fixed #1138 - AboutActivity UI enhancement.
OneBusAway/onebusaway-android pull request #1148
Opened 2024-03-08 11:46 UTC by sebesti0n

Fixed #1138
Preview:

https://github.com/OneBusAway/onebusaway-android/assets/114914556/38b1dcd1-e286-49ff-9a18-c8d0efe215e4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

2024-03-08 21:09 UTC, neeldoshii requested changes

2024-03-08 21:09 UTC, neeldoshii commented on onebusaway-android/src/main/java/org/onebusaway/android/ui/AboutActivity.java
> +//        builder.append("\n\n");
If not needed, can we remove the comments? @sebesti0n

2024-03-08 21:26 UTC, neeldoshii approved these changes

2024-03-11 00:16 UTC, aaronbrethorst approved these changes
Generally, I think this looks great, and I appreciate you tackling it. I have a couple minor quibbles with the content layout and text, but I'll follow up with another PR that covers them shortly.

2024-03-11 00:17 UTC, merged

2024-03-11 00:19 UTC, aaronbrethorst commented
@sebesti0n fyi - see #1160