feat: added custom volume preference for "My Reminder"
OneBusAway/onebusaway-android pull request #1151
Opened 2024-03-09 04:04 UTC by sebesti0n

Fixed #802 
Preview:

https://github.com/OneBusAway/onebusaway-android/assets/114914556/26a0e7cb-c9b7-48ed-8751-b2dcb0364ff4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

2024-03-15 03:57 UTC, aaronbrethorst requested changes
I see a handful of code changes. Mostly nitpicks. Let me know when this is ready for re-review and thanks for the feature!

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/java/org/onebusaway/android/ui/PreferencesActivity.java
> +
please watch your newlines in between instance variables. one blank newline is fine; two looks strange.

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/java/org/onebusaway/android/ui/PreferencesActivity.java
> +        mVolumePref = findPreference("reminder_volume");
extract to resources like the other preferences keys.

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/java/org/onebusaway/android/ui/PreferencesActivity.java
> +        final int progress = settings.getInt("reminder_volume",100);
same here as above with the preferences key

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/java/org/onebusaway/android/ui/PreferencesActivity.java
> +                                setReminderVolume(seekBar.getProgress());
there's an extra tab on this line, please remove it.

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/java/org/onebusaway/android/ui/PreferencesActivity.java
> +        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
if this feature only works on Android M and above, then it should only be displayed to users on Android M and above.

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/java/org/onebusaway/android/ui/PreferencesActivity.java
> +        if (audioManager != null) {
I recommend restructuring this method to use early returns.

```java
private void setReminderVolume(int progress) {
        AudioManager audioManager = null;
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
            audioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
        }
        
        if (audioManager == null) {
            return;
        }

        int maxVolume = audioManager.getStreamMaxVolume(AudioManager.STREAM_ALARM);
        int scaledVolume = (int) (progress / 100f * maxVolume);
        audioManager.setStreamVolume(AudioManager.STREAM_ALARM, scaledVolume, 0);
        SharedPreferences.Editor editor = PreferenceManager.getDefaultSharedPreferences(this).edit();
        editor.putInt("reminder_volume", progress);
        editor.apply();
    }
```

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/java/org/onebusaway/android/ui/PreferencesActivity.java
> +            editor.putInt("reminder_volume", progress);
resource string again

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/res/values-es/strings.xml
> +    <!--    reminder volume adjuster layout-->
please watch your spaces:

```
<!-- reminder volume adjuster layout -->
```

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/res/values-es/strings.xml
> +    <string name="reminder_volume_adjuster_title">volumen</string>
Capitalize the title

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/res/values-es/strings.xml
> +    <string name="save">guardar</string>
Change the string key from `save` to `reminder_volume_adjuster_save` and capitalize

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/res/values-fi/strings.xml
> +    <!--    reminder volume adjuster layout-->
same as above

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/res/values-fi/strings.xml
> +    <string name="save">"tallentaa "</string>
also, there shouldn't be double quotes inside the XML element here.

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/res/values-it/strings.xml
> +    <!--    reminder volume adjuster layout-->
same as above, including the double quotes inside the XML element

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/res/values-pl/strings.xml
> +    <!--    reminder volume adjuster layout-->
Same as above, including double quotes. Also, there are several space characters on the `save` string that need to be removed.

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/res/values/strings.xml
> +<!--    reminder volume adjuster layout-->
indent, spaces, save key, capitalize Save.

2024-03-15 03:57 UTC, aaronbrethorst commented on onebusaway-android/src/main/res/xml/preferences.xml
> +                android:key="reminder_volume"
resource key

2024-03-15 09:59 UTC, sebesti0n commented
> I see a handful of code changes. Mostly nitpicks. Let me know when this is ready for re-review and thanks for the feature!

Applied all changes

2024-03-15 15:18 UTC, aaronbrethorst requested changes
Code looks good, however I see that this feature is controlling the system-wide alarm volume, not just the volume of OBA-generated alerts. That seems crucial to me, because otherwise we should simply defer to the built-in control for changing volume.

2024-03-18 05:12 UTC, sebesti0n commented
> Code looks good, however I see that this feature is controlling the system-wide alarm volume, not just the volume of OBA-generated alerts. That seems crucial to me, because otherwise we should simply defer to the built-in control for changing volume.

Thank you for correcting me. I researched the issue and found that there is no built-in functionality for changing the alarm volume of individual applications. Therefore, I think this could be implemented by decreasing the system volume just before the reminder, and after the reminder is over, returning the system volume to its previous level.

2024-05-15 16:42 UTC, closed without merging