Fixes #603 : Additional Trip Preferences Layout clipped on smaller devices
OneBusAway/onebusaway-android pull request #1167
Opened 2024-03-12 19:10 UTC by neeldoshii

## Fixes
* Fixes #603 #1158 

## Testing Instructions
1. Make Sure you have smaller device or emulator of resolution less than 200x440
2. Oepn the navigation drawer
3. Click on Plan a trip(beta)
4. From the top three dot -> Addition Trip Preference

## Screenshots

### Before 
<img src = https://github.com/OneBusAway/onebusaway-android/assets/60827173/36631dab-511a-446c-8757-6c320739d0b5 width = 50% height = 50%>

### After
<img src = https://github.com/OneBusAway/onebusaway-android/assets/60827173/64465753-7429-4afa-bdb1-feaacba30e00 width = 50% height = 50%>

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

2024-03-12 19:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OneBusAway/onebusaway-android?pullRequest=1167) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OneBusAway/onebusaway-android?pullRequest=1167) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OneBusAway/onebusaway-android?pullRequest=1167) it.</sub>

2024-03-12 19:13 UTC, neeldoshii commented on onebusaway-android/src/main/res/layout/trip_plan_advanced_settings_dialog.xml
> +    <com.google.android.material.textfield.TextInputLayout
Maintainer Note :
Replaced EditText with TextInputLayout as said by #537

2024-03-12 19:14 UTC, neeldoshii commented on onebusaway-android/src/main/res/layout/trip_plan_advanced_settings_dialog.xml
> +    <com.google.android.material.textfield.TextInputLayout
Maintainer Note:
No speakable text present

From Accessibility side (Content Description) what should text should be added here?

2024-03-12 19:20 UTC, neeldoshii commented
Should I perform squash merge or perform rebase?

2024-03-12 19:24 UTC, aaronbrethorst commented
squash your commits, please

2024-03-21 23:58 UTC, aaronbrethorst requested changes
this is an improvement on _extremely_ small screens, but I am seeing some major regressions on larger (i.e. normal sized screens).

Given that extremely small screens (you mentioned below 200px) are incredibly rare, I wonder if we might be better off leaving this as is.

## before

![before](https://github.com/OneBusAway/onebusaway-android/assets/2254/9738d816-01bd-4580-9fdd-13c9711a8249)

## after

![after](https://github.com/OneBusAway/onebusaway-android/assets/2254/666c9b11-3d02-46c9-96e3-0539d7a95cb4)

2024-05-06 17:26 UTC, aaronbrethorst commented
closing per my comments in march.

2024-05-06 17:26 UTC, closed without merging