Update TripService.java
OneBusAway/onebusaway-android pull request #1209
Opened 2024-04-26 23:26 UTC by lchengl02

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

2024-04-26 23:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OneBusAway/onebusaway-android?pullRequest=1209) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OneBusAway/onebusaway-android?pullRequest=1209) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OneBusAway/onebusaway-android?pullRequest=1209) it.</sub>

2024-04-26 23:36 UTC, aaronbrethorst requested changes
This needs an explanation.

2024-04-26 23:42 UTC, lchengl02 reviewed
Optimized the code structure of setting alerts for different Android Versions

2024-04-27 04:33 UTC, closed without merging

2024-04-27 04:33 UTC, aaronbrethorst commented
no thanks. I intentionally moved this code away from the structure you're proposing. Also, just a general tip about commit messages: you need to write them such that they will explain not just the what but also the _why_ so that they make sense to someone reading through your changes years from now.