Fix dark mode support for alert dialog on Android 15
OneBusAway/onebusaway-android pull request #1250
Opened 2024-09-16 18:18 UTC by amrhossamdev

Fixes #1247.

## **Summary**

Alert dialogs were not functioning correctly on Android 15 when invoked from any `Fragment`, as noted in [ticket #1247](#1247). The issue did not affect alert dialogs called from activities, where they continued to work as expected.

## **Fix**

A custom alert dialog implementation was added across the application. The solution has been tested on Android 7, 11, 12, 13, 14, and 15, using Google Pixel 8 Pro and Ximote Note 8 Pro devices.

## **Screenshot**

<div align="center">

<table>
  <tr>
    <td>
      <strong>Before:</strong><br>
      <img src="https://github.com/user-attachments/assets/d0dbcb36-73d9-48c9-8d58-236919cf3825" width="300" />
    </td>
    <td>
      <strong>After:</strong><br>
      <img src="https://github.com/user-attachments/assets/7ba0940c-832f-4263-aed6-735d79632f9f" width="300" />
    </td>
  </tr>
</table>

</div>

## **TODO**
- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

2024-09-19 11:48 UTC, advait-zx commented
hey @amrhossamdev can i work on it?

2024-09-19 15:53 UTC, amrhossamdev commented
> **[advait-zx](/advait-zx) ** commented

Hi advait it's already a fix.

2024-09-24 00:43 UTC, aaronbrethorst requested changes
be sure to rebase this against main so you don't have conflicting, identical commits in your PR and be sure to remove the stray `K` character!

2024-09-24 00:43 UTC, aaronbrethorst commented on onebusaway-android/build.gradle
> +        versionCode 147
you'll need to rebase this PR against main.

2024-09-24 00:43 UTC, aaronbrethorst commented on onebusaway-android/src/main/res/values/themes.xml
> +K
typo

2024-09-24 00:49 UTC, amrhossamdev commented on onebusaway-android/src/main/res/values/themes.xml
> +K
sorry

2024-09-24 01:16 UTC, amrhossamdev commented
I will close this and i will rebase from the main branch.

2024-09-24 01:16 UTC, closed without merging