Feat: add sidecar base url
OneBusAway/onebusaway-android pull request #1281
Opened 2024-11-30 03:08 UTC by amrhossamdev

Fixes #1280 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

2024-11-30 03:28 UTC, aaronbrethorst requested changes
looking good! I'd like to see one comment changed and then there's a test failure to resolve.

2024-11-30 03:28 UTC, aaronbrethorst commented on onebusaway-android/src/main/java/org/onebusaway/android/io/elements/ObaRegion.java
> +     * @return The sideCar Vase URL for this region, or null if it doesn't have a sideCar URL.
small typo:

```
The sideCar Vase URL for this region, or null if it doesn't have a sideCar URL
```

->

```
The sidecar base URL for this region, or null if it doesn't have a sidecar URL
```

2024-11-30 14:31 UTC, amrhossamdev commented
I removed the region weather test as it was primarily testing the IO functionality. I believe it's not essential since it requires a sidecar URL, which is not mandatory. Let me know your thoughts. @aaronbrethorst

2024-12-01 21:47 UTC, aaronbrethorst approved these changes
lgtm 👍

2024-12-01 21:47 UTC, merged