Fixed #851 - added filter by arrivals/departures option to ArrivalsListFragment
OneBusAway/onebusaway-android pull request #1290
Opened 2024-12-26 16:53 UTC by viditpawar0

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

Screenshot:
![Screenshot_20241226_221623_OneBusAway](https://github.com/user-attachments/assets/9938c689-9a7e-4fe2-86c7-6bc18b22a2e1)

2024-12-27 08:23 UTC, amrhossamdev commented
Hi @viditpawar0, thanks for your contribution! Could you please rebase it against the main branch?

2024-12-27 12:05 UTC, viditpawar0 commented
@amrhossamdev Sure. But the branch is up to date with the main branch.

2024-12-27 17:43 UTC, amrhossamdev commented
@viditpawar0 These commits are already part of the main branch but are being shown again because your branch's history diverged from main before those commits were merged.

Rebase Your Branch on main To clean up the commit history, and always start a new branch from main. Before starting new work, ensure your branch is up-to-date. Start with a fresh branch each time to avoid inheriting old commits.

2024-12-28 10:06 UTC, amrhossamdev requested changes
Overall, it looks great! However, could you please include more information in the PR regarding your approach and logic? This will help me understand better.

2024-12-28 10:06 UTC, amrhossamdev commented on onebusaway-android/src/main/java/org/onebusaway/android/util/ArrivalInfoUtils.java
> +                    if (shouldAddEta(info) && shouldAddArrivalFilter(info, arrivalFilter)) {
Could you please explain your logic here ?

2024-12-28 10:06 UTC, amrhossamdev commented on onebusaway-android/src/main/java/org/onebusaway/android/util/ArrivalInfoUtils.java
> +                if (shouldAddEta(info) && shouldAddArrivalFilter(info, arrivalFilter)) {
and here can you explain the logic

2025-02-10 23:23 UTC, amrhossamdev commented
closing due inactivity

2025-02-10 23:23 UTC, closed without merging